config/routes.rb
Rails.application.routes.draw do

  get 'prices' => 'prices#index', as: :prices
  resources :posts
  resources :practitioners

  post '/contacts' => 'visitors#contacts', as: :contacts
  get '/contacts/success' => 'visitors#contacts_success', as: :contacts_success
  root 'visitors#index'
  resources :introductions
  resources :careers
  resources :businesses
  devise_for :users, controllers: {
    invitations: 'users/invitations',
  }

  namespace :app, path: 'app' do
    get 'settings' => 'dashboards#settings', as: :settings
    get 'dashboard' => 'dashboards#index', as: :dashboard

    resources :blogs
    resources :practitioners do
      collection do
        post :sync
      end
    end
    resources :billable_items do
      collection do
        post :sync
      end
    end
    resources :users do
      member do
        post :resend_invitation
      end
    end
    resources :home_settings
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :phone, :email, :address, :facebook, :twitter, :linkedin)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= form_with(model: business, local: true) do |form| %>
  <% if business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% business.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :business_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :business_phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :business_email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :business_address %>
  </div>

  <div class="field">
    <%= form.label :facebook %>
    <%= form.text_field :facebook, id: :business_facebook %>
  </div>

  <div class="field">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, id: :business_twitter %>
  </div>

  <div class="field">
    <%= form.label :linkedin %>
    <%= form.text_field :linkedin, id: :business_linkedin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Show', @business %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/index.html.erb
<h1>Business Details</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.name %></td>
        <td><%= business.phone %></td>
        <td><%= business.email %></td>
        <td><%= link_to 'Show', business %></td>
        <td><%= link_to 'Edit', edit_business_path(business) %></td>
        <td><%= link_to 'Destroy', business, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Business', new_business_path %>

app/views/businesses/new.html.erb
<h1>New Business</h1>

<%= render 'form', business: @business %>

<%= link_to 'Back', businesses_path %>

app/views/businesses/show.html.erb
<h1>Business</h1>
<p>
  <strong>Name:</strong>
  <%= @business.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @business.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @business.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @business.address %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @business.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @business.twitter %>
</p>

<p>
  <strong>Linkedin:</strong>
  <%= @business.linkedin %>
</p>

<%= link_to 'Edit', edit_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>