config/routes.rb
Rails.application.routes.draw do

  get 'prices' => 'prices#index', as: :prices
  resources :posts
  resources :practitioners

  post '/contacts' => 'visitors#contacts', as: :contacts
  get '/contacts/success' => 'visitors#contacts_success', as: :contacts_success
  root 'visitors#index'
  resources :introductions
  resources :careers
  resources :businesses
  devise_for :users, controllers: {
    invitations: 'users/invitations',
  }

  namespace :app, path: 'app' do
    get 'settings' => 'dashboards#settings', as: :settings
    get 'dashboard' => 'dashboards#index', as: :dashboard

    resources :blogs
    resources :practitioners do
      collection do
        post :sync
      end
    end
    resources :billable_items do
      collection do
        post :sync
      end
    end
    resources :users do
      member do
        post :resend_invitation
      end
    end
    resources :home_settings
  end
end

app/models/billable_item.rb
# == Schema Information
#
# Table name: billable_items
#
#  id                     :integer          not null, primary key
#  name                   :string
#  item_number            :string
#  price                  :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  business_id            :integer
#  practitioner_full_name :string
#  owner_health_id        :integer
#  business_name          :string
#

class BillableItem < ApplicationRecord
  belongs_to :business

  validates_presence_of :name, :item_number, :price

  validates :price, numericality: { greater_than: 0 }
end

app/controllers/app/billable_items_controller.rb
class App::BillableItemsController < App::BaseController
  before_action :set_billable_item, only: [:show, :edit, :update, :destroy]

  # GET /billable_items
  # GET /billable_items.json
  def index
    @billable_items = current_business.billable_items.all
  end

  # GET /billable_items/1
  # GET /billable_items/1.json
  def show
  end

  # GET /billable_items/new
  def new
    @billable_item = current_business.billable_items.new
  end

  # GET /billable_items/1/edit
  def edit
  end

  def create
    @billable_item = current_business.billable_items.new(billable_item_params)

    if @billable_item.save
      redirect_to app_billable_items_path,
                  notice: 'Billable item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @billable_item.update(billable_item_params)
      redirect_to app_billable_items_path,
                  notice: 'Billable item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @billable_item.destroy

    redirect_to app_billable_items_path,
                notice: 'Billable item was successfully destroyed.'
  end

  def sync
    if OwnerHealth::Sync::BillableItem.call(current_business.home_setting)
      redirect_to app_billable_items_path,
                  notice: 'Billable items has been sync successfully.'
    else
      redirect_to app_billable_items_path,
                  alert: 'Something was wrong. Please try again.'
    end
  end

  private
    def set_billable_item
      @billable_item = current_business.billable_items.find(params[:id])
    end

    def billable_item_params
      params.require(:billable_item).permit(:name, :item_number, :price, :practitioner_full_name)
    end
end

app/helpers/billable_items_helper.rb
module BillableItemsHelper
end

app/views/app/billable_items/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for [:app, billable_item] do |f| %>
      <%= f.input :name %>
      <%= f.input :item_number %>
      <%= f.input :price %>
      <%= f.input :practitioner_full_name %>

      <button class="btn btn-outline-primary">
        Submit
      </button>
    <% end %>
  </div>
</div>

app/views/app/billable_items/edit.html.erb
<h1>Editing Billable Item</h1>

<%= render 'form', billable_item: @billable_item %>

app/views/app/billable_items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-sm-6">
    <h1>Billable Items</h1>
  </div>
  <div class="col-sm-6 text-right">
    <a class="btn btn-outline-success btn-sm" data-method="POST" href="<%= sync_app_billable_items_path %>">
      Sync Owner Health
    </a>
    <% if current_business.home_setting&.last_sync_billable_items_at %>
      <small>Last Sync At: <%= current_business.home_setting&.last_sync_billable_items_at.try(:strftime, "%d %b, %Y %I:%M%P") %></small>
    <% end %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Item number</th>
      <th>Price</th>
      <th>Practitioner full name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @billable_items.each do |billable_item| %>
      <tr>
        <td><%= billable_item.name %></td>
        <td><%= billable_item.item_number %></td>
        <td><%= billable_item.price %></td>
        <td><%= billable_item.practitioner_full_name %></td>
        <td><%= link_to 'Show', app_billable_item_path(billable_item) %></td>
        <td><%= link_to 'Edit', edit_app_billable_item_path(billable_item) %></td>
        <td><%= link_to 'Destroy', app_billable_item_path(billable_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Billable Item', new_app_billable_item_path %>

app/views/app/billable_items/new.html.erb
<h1>New Billable Item</h1>

<%= render 'form', billable_item: @billable_item %>

app/views/app/billable_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @billable_item.name %>
</p>

<p>
  <strong>Item number:</strong>
  <%= @billable_item.item_number %>
</p>

<p>
  <strong>Price:</strong>
  <%= @billable_item.price %>
</p>

<p>
  <strong>Practitioner:</strong>
  <%= @billable_item.practitioner_full_name %>
</p>

<%= link_to 'Edit', edit_billable_item_path(@billable_item) %> |
<%= link_to 'Back', billable_items_path %>