config/routes.rb
Rails.application.routes.draw do

  get 'prices' => 'prices#index', as: :prices
  resources :posts
  resources :practitioners

  post '/contacts' => 'visitors#contacts', as: :contacts
  get '/contacts/success' => 'visitors#contacts_success', as: :contacts_success
  root 'visitors#index'
  resources :introductions
  resources :careers
  resources :businesses
  devise_for :users, controllers: {
    invitations: 'users/invitations',
  }

  namespace :app, path: 'app' do
    get 'settings' => 'dashboards#settings', as: :settings
    get 'dashboard' => 'dashboards#index', as: :dashboard

    resources :blogs
    resources :practitioners do
      collection do
        post :sync
      end
    end
    resources :billable_items do
      collection do
        post :sync
      end
    end
    resources :users do
      member do
        post :resend_invitation
      end
    end
    resources :home_settings
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billable_item.rb
# == Schema Information
#
# Table name: billable_items
#
#  id                     :integer          not null, primary key
#  name                   :string
#  item_number            :string
#  price                  :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  business_id            :integer
#  practitioner_full_name :string
#  owner_health_id        :integer
#  business_name          :string
#

class BillableItem < ApplicationRecord
  belongs_to :business

  validates_presence_of :name, :item_number, :price

  validates :price, numericality: { greater_than: 0 }
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :string
#  content            :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#

class Blog < ApplicationRecord
  has_attached_file :photo, styles: { medium: "450x450>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/business.rb
# == Schema Information
#
# Table name: businesses
#
#  id         :integer          not null, primary key
#  name       :string
#  phone      :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  address    :string
#  facebook   :string
#  twitter    :string
#  linkedin   :string
#

class Business < ApplicationRecord

  has_many :users
  has_one :business
  has_one :home_setting
  has_many :practitioners
  has_many :billable_items
  has_many :blogs

end

app/models/home_setting.rb
# == Schema Information
#
# Table name: home_settings
#
#  id                          :integer          not null, primary key
#  introduction_title          :string
#  introduction_description    :text
#  careers_title               :string
#  careers_description         :text
#  business_id                 :integer
#  business_name               :string
#  business_phone              :string
#  business_address            :string
#  business_email              :string
#  api_key                     :string
#  last_sync_practitioners_at  :datetime
#  last_sync_billable_items_at :datetime
#

class HomeSetting < ApplicationRecord
  belongs_to :business
end

app/models/practitioner.rb
# == Schema Information
#
# Table name: practitioners
#
#  id                  :integer          not null, primary key
#  first_name          :string
#  last_name           :string
#  profession          :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  business_id         :integer
#  full_name           :string
#  summary             :string
#  registration        :string
#  owner_health_id     :integer
#  business_name       :string
#

class Practitioner < ApplicationRecord
  PROFESSIONS = [
    "Physiotherapist",
    "Podiatrist",
    "Occupational Therapist",
    "Psychologist",
    "Dietitian",
    "Exercise Physiologist",
    "Speech Therapist",
    "Social Worker",
    "Doctor",
    "Registered Nurse",
    "Enrolled Nurse",
    "Case Manager",
    "Massage Therapist",
    "Myotherapist",
    "Therapy Assistant",
    "Support Worker",
    "Acupuncturist",
    "Osteopath",
    "Chiropractor"
  ]

  belongs_to :business

  after_validation :set_full_name

  has_attached_file :avatar, styles: { medium: "450x450>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  validates_presence_of :first_name, :last_name, :profession
  validates :profession, inclusion: { in: PROFESSIONS }

  private
  def set_full_name
    if first_name_changed? || last_name_changed?
      self.full_name = [first_name, last_name].join(" ") 
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  business_id            :integer
#  role                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = [
    ROLE_ADMIN = 'Admin',
    ROLE_PRACTITIONER = 'Practitioner'
  ]

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :business

  def admin?
    self.role == ROLE_ADMIN
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'sub_page'
  before_action :set_post, only: [:show]

  def show
    @setting = HomeSetting.first
  end

  private
  def set_post
    @post = Blog.find params[:id]
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  layout "visitors", only: [:index]
  layout 'sub_page', only: [:contacts_success]

  def index
    @setting = HomeSetting.first
  end


  def contacts
    @setting = HomeSetting.first
    ApplicationMailer.contact_mailer(@setting, params).deliver_now
    redirect_to contacts_success_path
  end

  def contacts_success
    @setting = HomeSetting.first
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_money amount
    money = Money.from_amount amount.to_f, :usd
    money.format
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/introductions_helper.rb
module IntroductionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practitioners_helper.rb
module PractitionersHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_blog.html.erb
<!-- Blog Section -->
<section id="blog" class="section">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Recent Blog</h2>
      <hr class="lines">
    </div>
    <div class="row">
      <div class="col-md-12 justify-content-md-center">
        <div class="blogs-slider owl-carousel owl-theme">
          <% Blog.find_each do |blog| %>
            <div class="blog-item">
              <div class="blog-item-wrapper">
                <div class="blog-item-img">
                  <a href="<%= post_path(blog) %>">
                    <%= image_tag blog.photo.url, class: 'img-responsive', alt: "Mobile Physiotherapist" %>
                  </a>
                </div>
                <div class="blog-item-text">
                  <h3>
                    <a href="<%= post_path(blog) %>"><%= blog.title %></a>
                  </h3>
                  <p>
                    <%= blog.description %>
                  </p>
                  <a href="<%= post_path(blog) %>" class="btn-rm">Read More <i class="lnr lnr-arrow-right"></i></a>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- blog Section End -->

app/views/visitors/_book_online.html.erb
<!-- Start Video promo Section -->
<section class="video-promo section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
          <div class="video-promo-content text-center">
            <h2 class="wow zoomIn" data-wow-duration="1000ms" data-wow-delay="100ms">Book Appointment Online</h2>
            <a href="https://owner.health/bookings" class="btn btn-border wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">Book Now</a>
          </div>
      </div>
    </div>
  </div>
</section>
<!-- End Video Promo Section -->

app/views/visitors/_careers.html.erb
<!-- Portfolio Section -->
<section class="section bg-white-liac">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title"><%= @setting.careers_title %></h2>
      <hr class="lines">
      <br>
      <div class="row">
        <div class="col-md-6">
          <%= image_tag 'why-onwer-health.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
        </div>
        <div class="col-md-6">
          <div class="section-subtitle">
            <%= simple_format @setting.careers_description %>
          </div>
          <br>
          <a href="https://owner.health/bookings" class="btn btn-common wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">Find Out More</a>
        </div>
      </div>
    </div>
</section>
<!-- Portfolio Section Ends -->

app/views/visitors/_footer.html.erb
<!-- Contact Section Start -->
<section id="contact" class="section" data-stellar-background-ratio="-0.2">
  <div class="contact-form">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-6 col-xs-12">
          <div class="contact-us">
            <h3>Contact With us</h3>
            <div class="contact-address">
              <p><%= @setting.business_address %></p>
              <p class="phone">Phone: <span><%= @setting.business_phone %></span></p>
              <p class="email">E-mail: <span><%= @setting.business_email %></span></p>
            </div>
            <div class="social-icons">
              <ul>
                <li class="facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="linkedin"><a href="#"><i class="fa fa-linkedin"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-6 col-sm-6 col-xs-12">
          <div class="contact-block">
            <%= simple_form_for :contacts, url: contacts_path, html: { novalidate: false } do |f|%>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required="true">
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <input type="email" placeholder="Your Email" id="email" class="form-control" name="email" required="true">
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <textarea class="form-control" id="message" name="message" placeholder="Your Message" rows="8" required="true"></textarea>
                  </div>
                  <div class="submit-button text-center">
                    <button class="btn btn-common" type="submit">Send Message</button>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Contact Section End -->

<!-- Footer Section Start -->
<footer>
  <div class="container">
    <div class="row">
      <!-- Footer Links -->
      <div class="col-lg-6 col-sm-6 col-xs-12">
        <ul class="footer-links">
          <li>
            <a href="<%= new_user_session_path %>">Website Admin Login</a>
          </li>
        </ul>
      </div>
      <div class="col-lg-6 col-sm-6 col-xs-12">
        <div class="copyright">
          <p><a href="https://owner.health">Powered by Owner Health</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- Footer Section End -->

<!-- Go To Top Link -->
<a href="#" class="back-to-top">
  <i class="lnr lnr-arrow-up"></i>
</a>

<div id="loader">
  <div class="spinner">
    <div class="double-bounce1"></div>
    <div class="double-bounce2"></div>
  </div>
</div>

app/views/visitors/_header.html.erb
<!-- Header Section Start -->
<header id="hero-area" data-stellar-background-ratio="0.5">
  <!-- Navbar Start -->
  <nav class="navbar navbar-expand-lg fixed-top scrolling-navbar indigo">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <a href="<%= root_path %>" class="navbar-brand">
          <img class="img-fulid logo-brand" src="<%= asset_path('logo.png') %>" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
          <i class="lnr lnr-menu"></i>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="main-navbar">
        <ul class="navbar-nav mr-auto w-100 justify-content-end">
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#"><%= @setting.business_phone %></a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="https://owner.health/bookings">Book Online</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="https://owner.health/app/dashboard">Practitioner Login</a>
          </li>
        </ul>
      </div>
    </div>

    <!-- Mobile Menu Start -->
    <ul class="mobile-menu">
        <li class="nav-item">
          <a class="nav-link page-scroll" href="#hero-area">+44 20 7437 5009</a>
        </li>
        <li class="nav-item">
          <a class="nav-link page-scroll" href="https://owner.health/bookings">Book Online</a>
        </li>
        <li class="nav-item">
          <a class="nav-link page-scroll" href="https://owner.health/app/dashboard">Practitioner Login</a>
        </li>
    </ul>
    <!-- Mobile Menu End -->

  </nav>
  <!-- Navbar End -->


  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-10">
        <div class="contents text-center">
          <h1 class="wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="0.3s"><%= @setting.business_name %></h1>
          <p class="lead larger-size  wow fadeIn" data-wow-duration="1000ms" data-wow-delay="400ms">We Serice All London Areas</p>
          <form action="https://owner.health/au/bookings">
            <div class="form-group">
              <input type="text" class="form-control text-center" id="booking-address" name="location" placeholder="Enter your address" required>
              <div class="help-block with-errors"></div>
            </div>
            <button class="btn btn-common wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">
              Search
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Header Section End -->

app/views/visitors/_how_does_it_work.html.erb
<!-- Portfolio Section -->
<section class="section bg-white-liac">
  <!-- Container Starts -->
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">How does it work?</h2>
      <hr class="lines">
      <br>
      <div class="row text-center">
        <div class="col-md-3">
          <%= image_tag '004-search.png', class: 'icon-works', alt: "Home Physiotherapist" %>
          <p class="icon-black-text" >Search Local Area.</p>
        </div>
        <div class="col-md-3">
          <%= image_tag '003-user.png', class: 'icon-works', alt: "Home Physiotherapist" %>
          <p class="icon-black-text" >Select Practitioner.</p>
        </div>
        <div class="col-md-3">
          <%= image_tag '002-calendar.png', class: 'icon-works', alt: "Home Physiotherapist" %>
          <p class="icon-black-text" >Book Online.</p>
        </div>
        <div class="col-md-3">
          <%= image_tag '001-car.png', class: 'icon-works', alt: "Home Physiotherapist" %>
          <p class="icon-black-text" >Home Visit.</p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Portfolio Section Ends -->

app/views/visitors/_introduction.html.erb
<!-- Introduction Section Start -->
<section id="services" class="section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title wow fadeIn" data-wow-duration="1000ms" data-wow-delay="0.3s">
        <%= @setting.introduction_title %>
      </h2>
      <hr class="lines wow zoomIn" data-wow-delay="0.3s">
      <br>
      <div class="row">
        <div class="col-md-6 section-subtitle">
          <%= simple_format @setting.introduction_description %>
          <br>
          <a href="https://owner.health/bookings" class="btn btn-common wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">Book Online</a>
        </div>
        <div class="col-md-6">
          <%= image_tag 'joy.jpg', class: 'img-responsive', alt: "Mobile Physiotherapist" %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Introduction Section End -->

app/views/visitors/_pricing.html.erb
<!-- Start Pricing Table Section -->
<section class="section bg-white-liac">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Pricing</h2>
      <hr class="lines">
      <p class="section-subtitle">Each practitioner can set their own pricing.</p>
    </div>
    <div class="text text-center">
        <a href="<%= prices_path %>" class="btn btn-common wow fadeInUp">See Full Price List</a>
    </div>
  </div>
</section>

app/views/visitors/_search_local.html.erb
<!-- Start Video promo Section -->
<section class="video-promo section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
          <div class="video-promo-content text-center">
            <h2 class="wow zoomIn" data-wow-duration="1000ms" data-wow-delay="100ms">Search your local area</h2>
            <a href="https://owner.health/bookings" class="btn btn-border wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="400ms">Search</a>
          </div>
      </div>
    </div>
  </div>
</section>
<!-- End Video Promo Section -->

app/views/visitors/_team.html.erb
<!-- Team section Start -->
<section id="team" class="section">
  <div class="container">
    <div class="section-header">
      <h2 class="section-title">Our Team</h2>
      <hr class="lines">
    </div>
    <div class="row">
      <div class="col-md-12 justify-content-md-center">
        <div class="practitioners-slider owl-carousel owl-theme">
          <% Practitioner.find_each do |prac| %>
            <div class="single-team">
              <a href="<%= practitioner_path(prac) %>" class="avatar" style="background-image: url(<%= prac.avatar.url %>)">
              </a>
              <div class="team-details">
                <div class="team-inner">
                  <a href="<%= practitioner_path(prac) %>" class="team-title"><%= prac.first_name %> <%= prac.last_name %></a>
                  <p><%= prac.profession %> <br><%= prac.registration %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Team section End -->

app/views/visitors/_testimonial.html.erb
<!-- Start Video promo Section -->
<section class="video-promo section">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
          <div class="video-promo-content text-center">
            <h2 class="wow zoomIn" data-wow-duration="1000ms" data-wow-delay="100ms">Find the best practitioners</h2>
            <p class="wow zoomIn" data-wow-duration="1000ms" data-wow-delay="100ms">Search your local area.</p>
            <div class="form-group">
              <input type="text" class="form-control text-center" id="name" name="name" placeholder="Enter your address" required data-error="Please enter your name">
              <div class="help-block with-errors"></div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>
<!-- End Video Promo Section -->

app/views/visitors/contacts_success.html.erb
<% content_for :page_heading, 'Contact'%>

<h4 style="color: #4CAF50;" class="text-center">
  Email has been sent to business sucessfully
</h4>

app/views/visitors/index.html.erb
<% content_for :seo_tags do %>
  <title><%= @setting.business_name %></title>
  <meta name="description" content="An uber style home physiotherapy service in the Greater London Area.">
<% end %>

<%= render 'visitors/header' %>

<%= render 'visitors/introduction' %>

<%= render 'visitors/how_does_it_work' %>

<%= render 'visitors/book_online' %>

<% if Practitioner.count > 0 %>
  <%= render 'visitors/team' %>
<% end %>

<%= render 'visitors/pricing' %>

<%= render 'visitors/search_local' %>

<% if Blog.count > 0 %>
  <%= render 'visitors/blog' %>
<% end %>

<%= render 'visitors/careers', section_class: 'bg-white-liac' %>

<%= render 'visitors/software' %>

<%= render 'visitors/footer' %>