config/routes.rb
Rails.application.routes.draw do

  get 'prices' => 'prices#index', as: :prices
  resources :posts
  resources :practitioners

  post '/contacts' => 'visitors#contacts', as: :contacts
  get '/contacts/success' => 'visitors#contacts_success', as: :contacts_success
  root 'visitors#index'
  resources :introductions
  resources :careers
  resources :businesses
  devise_for :users, controllers: {
    invitations: 'users/invitations',
  }

  namespace :app, path: 'app' do
    get 'settings' => 'dashboards#settings', as: :settings
    get 'dashboard' => 'dashboards#index', as: :dashboard

    resources :blogs
    resources :practitioners do
      collection do
        post :sync
      end
    end
    resources :billable_items do
      collection do
        post :sync
      end
    end
    resources :users do
      member do
        post :resend_invitation
      end
    end
    resources :home_settings
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  business_id            :integer
#  role                   :string
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ROLES = [
    ROLE_ADMIN = 'Admin',
    ROLE_PRACTITIONER = 'Practitioner'
  ]

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :business

  def admin?
    self.role == ROLE_ADMIN
  end
end

app/controllers/app/users_controller.rb
class App::UsersController < App::BaseController

  before_action :set_user, only: [
    :edit, :update, :destroy, :resend_invitation, :accept
  ]

  def index
    @users = current_business.users
  end

  def new
    @user = current_business.users.new role: User::ROLE_ADMIN
  end

  def create
    @user = current_business.users.new user_params
    @user.password = Devise.friendly_token.first(10)
    if @user.save
      @user.invite!(current_user)
      redirect_to app_users_path, notice: "User has beed created successfully"
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @user.delete
    redirect_to app_users_path, notice: "User has beed deleted successfully"
  end

  def update
    if @user.update user_params
      if params[:user][:password].present? && @user.invited_to_sign_up?
        @user.accept_invitation!
      end
      redirect_to app_users_path, notice: "User has beed updated successfully"
    else
      render :edit
    end
  end

  def resend_invitation
    if @user.invited_to_sign_up?
      @user.invite!
      flash[:notice] = 'Invitation email has been sent to the user.'
    else
      flash[:alert] = 'The user has already accepted invitation.'
    end

    redirect_to app_users_path
  end

  def accept
  end

  private
  def set_user
    @user = current_business.users.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  layout 'auth'
  private

  def invite_resource
    super do |u|
      u.skip_invitation = true
    end
  end

  def accept_resource
    resource = resource_class.accept_invitation!(update_resource_params)
    resource
  end
end

app/views/app/users/_form.html.erb
<%= simple_form_for [:app, @user] do |f| %>
  <%= f.input :email, required: true, autofocus: true %>
  <%= f.button :submit, class: "btn btn btn-success" %>
<% end %>

app/views/app/users/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h4>User information</h4>
    <%= render 'form' %>
  </div>
  <div class="col-sm-6">
    <h4>Change password</h4>
    <%= simple_form_for [:app, @user] do |f| %>
      <%= f.input :password, required: true %>
      <%= f.input :password_confirmation, required: true %>
      <%= f.button :submit, class: "btn btn btn-success", value: "Change password" %>
    <% end %>
</div>

app/views/app/users/index.html.erb
<h1>Users</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <%= link_to 'Show', app_user_path(user) %> |
          <%= link_to 'Edit', edit_app_user_path(user) %> |
          <%= link_to 'Destroy', app_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% if user.invited_to_sign_up? %>
          | <a href="<%= resend_invitation_app_user_path(user) %>" data-method="POST"
            data-confirm="Are you sure?">
            Resend invitation
          </a>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_app_user_path %>

app/views/app/users/new.html.erb
<h1>New user</h1>

<div class="row">
  <div class="col-sm-6">
    <%= render 'form' %>
  </div>
</div>